drop_cols: ['event_type_count_binvest_onboarding',
  'event_type_count_binvest_onboarding_back',
  'event_type_count_binvest_initial_screen',
  'event_type_count_card_new_request_confirm_sms',
  'event_type_count_card_new_select_type',
  'event_type_count_card_new_open_success',
  'event_type_count_complete_card',
  'event_type_count_card_new_send_open_request',
  'event_type_count_mainscreen_topbanner',
  'event_type_count_ecp_signing_password_input',
  'event_type_count_cash_loan_has_recent_applications_alert',
  'event_type_count_cl_bank_deeplink_cellinputactivated',
  'event_type_count_transfer_view_history_info',
  'event_type_count_card_new_error_form',
  'event_type_count_delivery_card_branch',
  'event_type_count_delivery_card_branch_confirm',
  'event_type_count_chat_start',
  'event_type_count_ecp_signing_password_wrong',
  'event_type_count_transfer_card_try_send',
  'event_type_count_transfer_dial_card_numbers',
  'event_type_count_transfer_card_success_send',
  'event_type_count_transfer_btw_my_acct_details_confirm',
  'event_type_count_transfer_btw_my_acct_success',
  'event_type_count_transfer_by_card_number_view',
  'event_type_count_transfer_btw_my_acct_confirmation_confirm',
  'event_type_count_transfer_btw_my_acct_view',
  'event_type_count_transfer_by_card_number_confirmation_confirm',
  'event_type_count_transfer_by_card_number_success',
  'event_type_count_transfer_scan_card_numbers',
  'event_type_count_toolbar_click_transfers',
  'event_type_count_profile_connectbank',
  'event_type_count_onboarding_error',
  'event_type_count_transfer_by_phone_view',
  'event_type_count_open_sys_settings',
  'event_type_count_toolbar_click_payments',
  'event_type_count_myproduct_settings_click',
  'event_type_count_payments_open_history_tab',
  'event_type_count_integrity_token_error',
  'event_type_count_onboarding_initial_next',
  'event_type_count_onboarding_location_denied',
  'event_type_count_toolbar_click_main',
  'event_type_count_initial_transfer_sber_rk',
  'event_type_count_open_prof',
  'event_type_count_ecp_release_close',
  'event_type_count_cash_loan_tax_menu_tapped',
  'event_type_count_cash_loan_doc_formation_status',
  'event_type_count_notifications_offer_button',
  'event_type_count_cl_repayment_method_info',
  'event_type_count_change_passcode_bio_start',
  'event_type_count_open_deposit',
  'event_type_count_delivery_card_courier',
  'event_type_count_cash_loan_refinance_banks',
  'event_type_count_cl_close',
  'event_type_count_ecp_signing_cancel',
  'event_type_count_onboarding_qr_scan_success',
  'event_type_count_onboarding_qr_manager_open',
  'event_type_count_deposit_open_success',
  'event_type_count_deposit_confirm',
  'event_type_count_deposit_open',
  'event_type_count_mainscreen_bottombanner',
  'event_type_count_deposit_transition_to_replenishment',
  'event_type_count_invalid_grant',
  'event_type_count_cash_loan_type_refinance_account_confirm',
  'event_type_count_logout',
  'event_type_count_delivery_card_order',
  'event_type_count_initial_cash_by_code',
  'event_type_count_cl_insurance_info_cellinputactivated',
  'event_type_count_initial_transfer_external_p2p',
  'event_type_count_ecp_signing_close',
  'event_type_count_payments_open_main_flow',
  'event_type_count_service_documents',
  'event_type_count_cash_loan_info_open',
  'event_type_count_binvest_product_offer',
  'event_type_count_payments_search',
  'event_type_count_payments_open_all_payments',
  'event_type_count_deposit_close',
  'event_type_count_deposit_close_confirm',
  'event_type_count_deposit_close_success',
  'event_type_count_open_customization_products',
  'event_type_count_account_open_confirm',
  'event_type_count_account_open_success',
  'event_type_count_account_open',
  'event_type_count_bonus_open',
  'event_type_count_transfers_view',
  'event_type_count_binvest_product_offer_open',
  'event_type_count_binvest_documents',
  'event_type_count_binvest_documents_back',
  'event_type_count_payments_main_flow_status',
  'event_type_count_complete_cash_by_code',
  'event_type_count_transfer_view_history_receipt',
  'event_type_count_open_exchange_rates',
  'event_type_count_widget_exchange',
  'event_type_count_transfer_new_fail',
  'event_type_count_onboarding_last_step',
  'event_type_count_onboarding_bio_start',
  'event_type_count_onboarding_bio_success',
  'event_type_count_onboarding_egov_sms_success',
  'event_type_count_onboarding_last_step_sms_success',
  'event_type_count_transfer_click_save_and_send',
  'event_type_count_profile_ecp',
  'event_type_count_card_activation_start',
  'event_type_count_moneybox_open',
  'event_type_count_cl_statement_trouble_continue',
  'event_type_count_ecp_release_cancel',
  'event_type_count_change_passcode_bio_success',
  'event_type_count_moneybox_goal',
  'event_type_count_open_customization_partition',
  'event_type_count_transfer_click_transferfee',
  'event_type_count_cash_loan_tax_alert',
  'event_type_count_card_activation_accepted',
  'event_type_count_card_activation_final',
  'event_type_count_transfer_swift_view',
  'event_type_count_transfer_zk_view',
  'event_type_count_moneybox_details',
  'event_type_count_moneybox_confirm',
  'event_type_count_moneybox_open_success',
  'event_type_count_transfer_swift_check_bic',
  'event_type_count_transfer_by_phone_confirmation_confirm',
  'event_type_count_transfer_by_phone_success',
  'event_type_count_transfer_by_phone_confirm',
  'event_type_count_transfer_swift_confirm_bin_on_input_screen',
  'event_type_count_tutorial_finish',
  'event_type_count_tutorial_start',
  'event_type_count_onboarding_initial_sms_cancel',
  'event_type_count_premium_detail_page',
  'event_type_count_crypto_main_page',
  'event_type_count_crypto_banner_click',
  'event_type_count_profile_exchangerate',
  'event_type_count_delivery_card_courier_success',
  'event_type_count_delivery_card_courier_confirm',
  'event_type_count_delivery_card_otp_success',
  'event_type_count_delivery_card_courier_cancel',
  'event_type_count_secretword_change',
  'event_type_count_secretword_change_success',
  'event_type_count_secretword_change_confirm',
  'event_type_count_card_activation_sms',
  'event_type_count_onboarding_prelogin_showcase',
  'event_type_count_onboarding_user_form_viewed',
  'event_type_count_onboarding_personal_data_viewed',
  'event_type_count_onboarding_contract_viewed',
  'event_type_count_onboarding_qr_send_failure',
  'event_type_count_binvest_sms_verification',
  'event_type_count_binvest_questionairy',
  'event_type_count_binvest_sms_verification_confirm',
  'event_type_count_binvest_questionairy_confirm',
  'event_type_count_binvest_sms_verification_in_progress',
  'event_type_count_binvest_documents_sign',
  'event_type_count_binvest_questionairy_back',
  'event_type_count_binvest_product_offer_declined',
  'event_type_count_binvest_account_declined_main',
  'event_type_count_binvest_account_declined_telegram',
  'event_type_count_transfer_swift_confirm_the_transfer',
  'event_type_count_onboarding_prelogin_showcase_product',
  'event_type_count_toolbar_click_services',
  'event_type_count_profile_appeals',
  'event_type_count_transfer_favorite_success',
  'event_type_count_account_close',
  'event_type_count_account_close_confirm',
  'event_type_count_transfer_frequent',
  'event_type_count_payments_category_info_banner_click',
  'event_type_count_cl_info_open',
  'event_type_count_onboarding_upload_image',
  'event_type_count_camera_permission_access',
  'event_type_count_onboarding_doc_scan',
  'event_type_count_onboarding_image_iin_validation',
  'event_type_count_cash_loan_tax_pay_tapped',
  'event_type_count_binvest_product_back',
  'event_type_count_binvest_product',
  'event_type_count_binvest_product_withdraw_withdraw_back',
  'event_type_count_binvest_product_withdraw',
  'event_type_count_binvest_product_withdraw_withdraw',
  'event_type_count_delivery_card_edit',
  'event_type_count_transfer_swift_confirm_btn_on_input_screen',
  'event_type_count_binvest_documents_view',
  'event_type_count_account_close_success',
  'event_type_count_transfer_by_card_number_details_confirm',
  'event_type_count_binvest_onboarding_open_account',
  'event_type_count_web_login_sms_success',
  'event_type_count_binvest_brokerage_account_history',
  'event_type_count_binvest_brokerage_account_top_up',
  'event_type_count_binvest_product_withdraw_withdraw_app',
  'event_type_count_binvest_product_top_up',
  'event_type_count_binvest_brokerage_account_top_up_top_up',
  'event_type_count_binvest_brokerage_account_top_up_sent',
  'event_type_count_binvest_brokerage_account_top_up_sms_verification_confirm',
  'event_type_count_binvest_brokerage_account_top_up_sms_verification',
  'event_type_count_transfer_zk_confirmation_confirm',
  'event_type_count_transfer_zk_details_confirm',
  'event_type_count_transfer_zk_success',
  'event_type_count_camera_permission_access_logout',
  'event_type_count_cash_loan_general_info',
  'event_type_count_cash_loan_calculator',
  'event_type_count_binvest_product_first_top_up',
  'event_type_count_binvest_product_offer_opened',
  'event_type_count_transfer_swift_confirm_btn_before_confirm_screen',
  'event_type_count_binvest_account_declined',
  'event_type_count_vklad_open',
  'event_type_count_payments_apply_filter',
  'event_type_count_binvest_sms_verification_cancel',
  'event_type_count_delivery_card_branch_success',
  'event_type_count_binvest_brokerage_account_top_up_error',
  'event_type_count_crypto_main_page_button_click',
  'event_type_count_onboarding_last_step_sms_cancel',
  'event_type_count_binvest_sms_verification_minimize',
  'event_type_count_binvest_sms_verification_error',
  'event_type_count_transfer_swift_success',
  'event_type_count_binvest_account_exist',
  'event_type_count_binvest_account_exist_partner_app']

final_cols: ['cli_age', 'dm5expsum', 'dm5incsum', 'finalkdn', 'session_len_std',
  'time_to_first_event', 'kanal_prodazh', 'median_time_diff_sec',
  'dm5dpd1gcvpsum', 'avg_events_per_minute', 'creditterm_rbl0',
  'branch', 'pd', 'time_span_sec', 'avg_session_len',
  'p95_time_diff_sec', 'weekend_events', 'dm6scoren6pd',
  'max_session_len', 'event_type_count_cl_back', 'avg_time_diff_sec',
  'std_time_diff_sec', 'event_type_count_transfer_initial',
  'sum_credit_kzt', 'event_type_count_new_product_preopen',
  'event_type_count_transfer_new_view_confirm_screen',
  'event_type_count_frequent_operations_click',
  'event_type_count_tab_history_transfers', 'time_to_last_event',
  'max_time_diff_sec',
  'event_type_count_cl_bank_instructions_cellinputactivated',
  'unique_ips', 'avg_lng_change', 'event_type_count_session_start',
  'event_type_count_transfer_view_history_screen',
  'event_type_count_ecp_initial',
  'event_type_count_transfer_new_success',
  'event_type_count_transfer_select_new_type', 'dm6scoren6',
  'event_type_count_onboarding_process_success', 'geo_jumps',
  'unique_versions', 'first_session_len', 'dependant_count',
  'event_type_count_login', 'event_type_count_enter_pin',
  'totalamount', 'purpose_loan', 'events_after_app',
  'events_before_app']

scaler_cols: ['time_span_sec', 'events_before_app', 'events_after_app',
       'avg_time_diff_sec', 'std_time_diff_sec', 'median_time_diff_sec',
       'max_time_diff_sec', 'min_time_diff_sec', 'p95_time_diff_sec',
       'avg_events_per_minute', 'time_to_first_event',
       'time_to_last_event', 'unique_event_types', 'top_event_type',
       'event_type_entropy', 'event_type_count_login',
       'event_type_count_session_start', 'event_type_count_session_end',
       'event_type_count_main_page', 'event_type_count_enter_pin',
       'event_type_count_transfer_initial',
       'event_type_count_initial_transfer_internal',
       'event_type_count_transfer_select_new_type',
       'event_type_count_transfer_new_success',
       'event_type_count_open_card',
       'event_type_count_cash_loan_uploading',
       'event_type_count_cash_loan_type_terms',
       'event_type_count_cash_loan_type_terms_confirm',
       'event_type_count_ecp_release_sms_inputactivated',
       'event_type_count_ecp_release_sms_initial',
       'event_type_count_ecp_release_initial',
       'event_type_count_ecp_initial',
       'event_type_count_ecp_release_success',
       'event_type_count_ecp_release_bio_initial',
       'event_type_count_ecp_release_bio_start',
       'event_type_count_ecp_release_sms_success',
       'event_type_count_cash_loan_complete',
       'event_type_count_ecp_signing_bio_success',
       'event_type_count_ecp_docs_signed',
       'event_type_count_ecp_signing_password_success',
       'event_type_count_ecp_signing_bio_start',
       'event_type_count_ecp_release_password_save',
       'event_type_count_ecp_signing_docs',
       'event_type_count_ecp_signing_bio_initial',
       'event_type_count_ecp_release_bio_success',
       'event_type_count_transfer_view_history_screen',
       'event_type_count_open_notification', 'unique_devices',
       'device_switched', 'switched_device_type', 'geo_jumps',
       'avg_lat_change', 'avg_lng_change', 'unique_ips',
       'unique_languages', 'unique_platforms', 'unique_os',
       'unique_versions', 'unique_countries', 'unique_regions',
       'unique_cities', 'unique_sessions', 'avg_session_len',
       'max_session_len', 'session_len_std', 'first_session_len',
       'last_session_len', 'session_len_diff', 'events_night',
       'events_day', 'events_evening', 'most_active_hour',
       'weekday_events', 'weekend_events',
       'event_type_count_cash_loan_initial_screen',
       'event_type_count_frequent_operations_click',
       'event_type_count_payments_open_tab', 'event_type_count_chat_view',
       'event_type_count_cl_amount_cellinputactivated',
       'event_type_count_cl_back', 'event_type_count_loan_term_view',
       'event_type_count_loan_type_click',
       'event_type_count_tab_history_transfers',
       'event_type_count_open_new_product_btn_click',
       'event_type_count_mainscreen_open_new_product_btn',
       'event_type_count_transfer_new_view_confirm_screen',
       'event_type_count_tab_loyalty',
       'event_type_count_onboarding_process_success',
       'event_type_count_onboarding_initial',
       'event_type_count_onboarding_initial_sms_success',
       'event_type_count_onboarding_pin_form',
       'event_type_count_cash_loan_data_sms_verification_start',
       'event_type_count_cl_bank_statemant_validvalueentered',
       'event_type_count_cl_bank_statemant_cellinputactivated',
       'event_type_count_cash_loan_personal_data',
       'event_type_count_cl_repayment_method_validvalueentered',
       'event_type_count_cl_duration_validvalueentered',
       'event_type_count_cl_amount_validvalueentered',
       'event_type_count_cl_insurance_validvalueentered',
       'event_type_count_cl_duration_cellinputactivated',
       'event_type_count_new_product_preopen',
       'event_type_count_cl_sms_validvalueentered',
       'event_type_count_cl_sms_cellinputactivated',
       'event_type_count_cash_loan_application_created_statement',
       'event_type_count_cash_loan_application_created',
       'event_type_count_cash_loan_error',
       'event_type_count_cl_bank_instructions_cellinputactivated',
       'event_type_count_cash_loan_under_consideration', 'purpose_loan',
       'opv_reason', 'kanal_prodazh', 'totalamount', 'sum_credit_kzt',
       'branch', 'application_isa0auto', 'dm5dpd1gcvpsum',
       'dm5dpd1salarysum', 'dm5expsum', 'dm5incsum', 'dm5inc', 'dm5exp',
       'dm7inc', 'dm7exp', 'dm6scoren6pd', 'dm6scoren6', 'finalkdn',
       'creditterm_rbl0', 'cli_age', 'gender', 'maritalstatus',
       'dependant_count', 'bki', 'vki', 'pd']

audio_features: ['total_segments',
       'avg_segment_duration', 'std_segment_duration', 'max_speaker_duration',
       'min_speaker_duration', 'dominant_speaker_ratio', 'speaking_turns_diff',
       'speech_density', 'avg_pause_between_segments',
       'audio_feature_0', 'audio_feature_1', 'audio_feature_2',
       'audio_feature_3', 'audio_feature_4', 'audio_feature_5',
       'audio_feature_6', 'audio_feature_7', 'audio_feature_8',
       'audio_feature_9', 'audio_feature_10', 'audio_feature_11',
       'audio_feature_12', 'audio_feature_13', 'audio_feature_14',
       'audio_feature_15', 'audio_feature_16', 'audio_feature_17',
       'audio_feature_18', 'audio_feature_19', 'audio_feature_20',
       'audio_feature_21', 'audio_feature_22', 'audio_feature_23',
       'audio_feature_24', 'audio_feature_25', 'audio_feature_26',
       'audio_feature_27', 'audio_feature_28', 'audio_feature_29',
       'audio_feature_30', 'audio_feature_31', 'audio_feature_32',
       'audio_feature_33', 'audio_feature_34', 'audio_feature_35',
       'audio_feature_36', 'audio_feature_37', 'audio_feature_38',
       'audio_feature_39', 'audio_feature_40', 'audio_feature_41',
       'audio_feature_42', 'audio_feature_43']